//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrIbrahimClinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationTreatment
    {
        public int Id { get; set; }
        public int ExaminationId { get; set; }
        public int TreatmentId { get; set; }
        public string Description { get; set; }
    
        public virtual Examination Examination { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
