//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrIbrahimClinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationDiagnosi
    {
        public int Id { get; set; }
        public Nullable<int> ExaminationId { get; set; }
        public int DisgnosisId { get; set; }
    
        public virtual Diagnosi Diagnosi { get; set; }
        public virtual Examination Examination { get; set; }
    }
}
